name: Telegram Motivation Bot



on:
  schedule:
    - cron: "30 5 * * *"    # 05:30 UTC
    - cron: "30 8 * * *"    # 08:30 UTC
    - cron: "15 11 * * *"   # 11:15 UTC
    - cron: "45 13 * * *"   # 13:45 UTC
    - cron: "0 15 * * *"    # 15:00 UTC
    - cron: "20 17 * * *"   # 17:20 UTC
    - cron: "10 20 * * *"   # 20:10 UTC
    - cron: "50 22 * * *"   # 22:50 UTC
  workflow_dispatch:


jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Bot

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python morning_bot.py
